[versions]
# Plugins
lombokPluginVersion = "8.12.2" #https://plugins.gradle.org/plugin/io.freefair.lombok
shadowPluginVersion = "8.3.5" #https://plugins.gradle.org/plugin/com.gradleup.shadow
runPaperPluginVersion = "2.3.1" #https://github.com/jpenilla/run-task
ymlPluginVersion = "0.6.0" #https://github.com/Minecrell/plugin-yml
paperweightVersion = "2.0.0-beta.8"
# CompileOnly
paperApiVersion = "1.16.5-R0.1-SNAPSHOT"
placeholderApiVersion = "2.11.6" #https://github.com/PlaceholderAPI/PlaceholderAPI
commandApiVersion = "9.4.2" #https://commandapi.jorel.dev/
hologramsVersion = "2.8.15" #https://github.com/DecentSoftware-eu/DecentHolograms/releases
worldEditVersion = "7.2.20" #https://github.com/EngineHub/WorldEdit/tags
worldGuardVersion = "7.0.7" #https://github.com/EngineHub/WorldGuard/tags
luckPermsVersion = "5.4" #https://mvnrepository.com/artifact/net.luckperms/api
# Implementation
commonsIoVersion = "2.18.0" #https://mvnrepository.com/artifact/commons-io/commons-io
helperVersion = "5.6.14" #https://github.com/lucko/helper
triumphGuiVersion = "3.1.11" #https://github.com/TriumphTeam/triumph-gui
guiceVersion = "7.0.0" #https://github.com/google/guice
hikariVersion = "6.2.1" #https://github.com/brettwooldridge/HikariCP
natsVersion = "2.20.5" #https://github.com/nats-io/nats.java
javatuplesVersion = "1.2" #https://mvnrepository.com/artifact/org.javatuples/javatuples/1.2
gsonVersion = "2.12.1" #https://mvnrepository.com/artifact/com.google.code.gson/gson
gsonExtrasVersion = "3.1.0" #https://mvnrepository.com/artifact/com.google.code.gson/gson-extras
adventureVersion = "4.19.0" #https://mvnrepository.com/artifact/net.kyori/adventure-api

wutilsConfigVersion = "2.7.9" #https://mymavenrepo.com/repo/SjKIru68icwwmC0qOtV7/me/wyne/WUtils-config/
wutilsConfigurablesVersion = "1.5.0" #https://mymavenrepo.com/repo/SjKIru68icwwmC0qOtV7/me/wyne/WUtils-configurables/
wutilsLogVersion = "3.1.3" #https://mymavenrepo.com/repo/SjKIru68icwwmC0qOtV7/me/wyne/WUtils-log/
wutilsi18nVersion = "3.3.13" #https://mymavenrepo.com/repo/SjKIru68icwwmC0qOtV7/me/wyne/WUtils-i18n/
wutilsCommonVersion = "1.1.2" #https://mymavenrepo.com/repo/SjKIru68icwwmC0qOtV7/me/wyne/WUtils-common/
wutilsJdbcVersion = "1.0.0" #https://mymavenrepo.com/repo/SjKIru68icwwmC0qOtV7/me/wyne/WUtils-jdbc/
wutilsJsonVersion = "1.0.0" #https://mymavenrepo.com/repo/SjKIru68icwwmC0qOtV7/me/wyne/WUtils-json/

[libraries]
# CompileOnly
paperApi = { module = "com.destroystokyo.paper:paper-api", version.ref = "paperApiVersion" }
placeholderApi = { module = "me.clip:placeholderapi", version.ref = "placeholderApiVersion" }
commandApi = { module = "dev.jorel:commandapi-bukkit-core", version.ref = "commandApiVersion" }
holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "hologramsVersion" }
worldEdit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldEditVersion" }
worldGuard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldGuardVersion" }
luckPerms = { module = "net.luckperms:api", version.ref = "luckPermsVersion" } 
# Implementation
commonsIo = { module = "commons-io:commons-io", version.ref = "commonsIoVersion" }
helper = { module = "me.lucko:helper", version.ref = "helperVersion" }
triumphGui = { module = "dev.triumphteam:triumph-gui", version.ref = "triumphGuiVersion" }
guice = { module = "com.google.inject:guice", version.ref = "guiceVersion" }
nats = { module = "io.nats:jnats", version.ref = "natsVersion" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikariVersion" }
javatuples = { module = "org.javatuples:javatuples", version.ref = "javatuplesVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
gsonExtras = { module = "org.danilopianini:gson-extras", version.ref = "gsonExtrasVersion" }
adventureApi = { module = "net.kyori:adventure-api", version.ref = "adventureVersion" }
adventureMini = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventureVersion" }

wutilsConfig = { module = "me.wyne:WUtils-config", version.ref = "wutilsConfigVersion" }
wutilsConfigugrables = { module = "me.wyne:WUtils-configurables", version.ref = "wutilsConfigurablesVersion" }
wutilsLog = { module = "me.wyne:WUtils-log", version.ref = "wutilsLogVersion" }
wutilsI18n = { module = "me.wyne:WUtils-i18n", version.ref = "wutilsi18nVersion" }
wutilsCommon = { module = "me.wyne:WUtils-common", version.ref = "wutilsCommonVersion" }
wutilsJdbc = { module = "me.wyne:WUtils-jdbc", version.ref = "wutilsJdbcVersion" }
wutilsJson = { module = "me.wyne:WUtils-json", version.ref = "wutilsJsonVersion" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombokPluginVersion" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadowPluginVersion" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaperPluginVersion" }
pluginYml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "ymlPluginVersion" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweightVersion" }
